# Generated by Django 3.0.8 on 2020-09-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_business_rules', '0002_auto_20180930_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dynamic_business_rules.ConditionSet'),
        ),
    ]
